name 'prep-box-cookbook'
maintainer 'Steven Praski'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures prep-box-cookbook'
long_description 'Installs/Configures prep-box-cookbook'
version '0.1.0'
